version: '3'
 
services:
  sftp-server:
    build:
      context: .
    hostname: sftp-server
    ports:
      - "2222:22"
    environment:
      SFTP_USER: ${SFTP_USER:-user}
      SFTP_PASS: ${SFTP_PASS:-password}
    volumes:
      - sftp-volume:/uploads

volumes:
  sftp-volume:
